title: SIBO Release Notes
description: SIBO Release Notes
theme: just-the-docs

logo: "/assets/images/logo-sibo-back-office.png"
favicon_ico: "/assets/images/favicon.ico"

url: https://sweetinn.github.io/release-notes-sibo

aux_links:
  Book A Demo: https://sibotech.io/book-a-demo


color_scheme: sibo
