title: SIBO Release Notes
description: SIBO Release Notes
theme: just-the-docs

logo: "/assets/images/logo-sibo-back-office.png"
favicon_ico: "/assets/images/favicon.ico"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
